### ISSUE TITLE
Unrealistic number for 0.5*Cd*A in train_res_temp.yaml

### ISSUE THREAD

**Issue by spencerm89** [NREL/altrios#4]
- [ ] copy calibrated number to other railcar types

8.44 is the fixed number given for half the drag area of the entire train in train_res_temp.yaml. This document doesn't state how many railcars the train is meant to have, but this drag area is implausibly low for any running train. The bearing friction shown in that document suggests a train length of around 55 cars. At these numbers about 6.7% of the resistance from bearing, rolling and aerodynamic drag will come from aerodynamic drag at 20 meters per second, this is vastly lower than the roughly 30% we should expect to come from aerodynamic drag according to the Davis equation. See the chart here at 40 mph https://pdfcoffee.com/tractive-effort-and-train-resistance-pdf-free.html.

Using this internal CFD simulation from my own startup, https://www.linkedin.com/feed/update/urn:li:activity:7044031752301879296/
a train with one locomotive and 9 intermodal wells should have a total drag area of 19.9. Extrapolating for 55 total cars (using the 8th well car to represent all of the interior cars) gives a total 1/2*CdA of 36.79 for the entire train. This is more than 4 times the given number in train_res_temp.yaml. Replacing 8.44 with 36.79 would give a drag fraction of resistance of 29% at 20 meters per second and no crosswinds, which is very reasonable and about what should be expected from the Davis equation. Of course aerodynamic drag should vary with car types and car counts, but while a single train number is used it needs to be more realistic and much larger than 8.44. Otherwise estimates of fuel/energy consumption will be much too low, adding horsepower will look much better in simulations then in the real world as large speed increases will be shown without much cost in added resistance and fuel, and aerodynamic improvement technologies will appear to have no benefit.

**Comment by spencerm89** [comment]
The 4 times difference suggests to me that a Davis equation number at the per axle level may be being used accidentally as a per car number and this would explain the issue.

**Comment by calbaker** [comment]
@SWRIganderson , can you read through this?

**Comment by calbaker** [comment]
@spencerm89 , we'll give this some thought.   Thanks for bringing it to our attention.  Everything has been calibrated and validated to test data so I think that if we're off by a factor of 4, we're off in a way that is self consistent, but naturally, if this is not formulated or documented correctly, we'll fix it.

**Comment by spencerm89** [comment]
[image: image.png]
print(np.max(train_sim.history.res_aero_newtons)/(np.max(train_sim.history.res_aero_newtons)+np.max(train_sim.history.res_bearing_newtons)+

 np.max(train_sim.history.res_rolling_newtons)))

Run this on the Altrios simulation you have that looks at force from
sources and produces the chart above. It gives aero resistance a proportion
of aero, bearing and rolling resistance of 6.7% at 20 meters per second, an
average of 2.7% over the trip as a whole. These aren't remotely plausible
numbers. The first should be close to 30%, making me think that you may
have substituted a Davis formula number for aero drag per axle as drag per
car or something like that.
